### ISSUE TITLE
/usr/bin/env: ‘python3\r’: No such file or directory

### ISSUE THREAD

**Issue by mother2110** [M4cs/DarkSpiritz#2]
[root:~/pentest/recon/DarkSpiritz]# ./start.py                                                                                                     
/usr/bin/env: ‘python3\r’: No such file or directory

**Comment by mother2110** [comment]
if I run pyhton start.py it does load but get...

[DSPF]> ?
Traceback (most recent call last):
  File "start.py", line 199, in <module>
    main()
  File "start.py", line 84, in main
    terminal = input(terminalname + colors.END)
  File "<string>", line 1
    ?
    ^
SyntaxError: unexpected EOF while parsing
[root:~/pentest/recon/DarkSpiritz]#

**Comment by M4cs** [comment]
Make sure you are running Python 3.5 or above.
